# Generated by Django 5.0.7 on 2024-08-01 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamedEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('namedentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petsclinic.namedentity')),
            ],
            options={
                'abstract': False,
            },
            bases=('petsclinic.namedentity',),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('namedentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petsclinic.namedentity')),
                ('birth_date', models.DateField()),
                ('visits', models.ManyToManyField(blank=True, related_name='pets', to='petsclinic.visit')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsclinic.pettype')),
            ],
            options={
                'abstract': False,
            },
            bases=('petsclinic.namedentity',),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='petsclinic.person')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=10)),
                ('pets', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='petsclinic.pet')),
            ],
            bases=('petsclinic.person',),
        ),
    ]
